repos:
    - repo: local
      hooks:
        - id: isort
          name: isort
          entry: poetry run isort -c tscopulas/
          language: system
          always_run: true
          pass_filenames: false
          
        - id: flake8
          name: flake8
          entry: poetry run flake8 --max-line-length=120 tscopulas/
          language: system
          always_run: true
          pass_filenames: false
          
        - id: pytest
          name: pytest
          entry: poetry run pytest -W ignore tests
          language: system
          always_run: false
          pass_filenames: false
