language: python
python:
  - "3.8"

before_script:
  - pip install poetry
  - poetry install

script:
  - skip

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - stage: lint
      name: Run isort and flake8
      script:
        - poetry run isort -c tscopulas/
        - poetry run flake8 tscopulas/ --max-line-length=120
    - stage: test
      name: Run pytests
      script: poetry run pytest -W ignore tests/ --cov=tscopulas/ --cov-fail-under=90
    - stage: deploy
      name: Deploy to GitHub Pages
      if: (NOT type IN (pull_request)) AND (branch = master) # only deploy if merging on master
      script:
        - poetry run sphinx-apidoc -o docs/ -f tscopulas/
        - cd docs && poetry run make html && cd ..
      deploy:
        provider: pages # deploy on github pages
        skip_cleanup: true
        github_token: "$token" # defined via the Travis interface
        local_dir: docs/_build/html/
